# Generated by Django 5.1.7 on 2025-04-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoModel',
            new_name='TransactionDemoModel',
        ),
    ]
